### PR TITLE
feat(docs): add DOCX and PDF export

### PR DESCRIPTION
**Pull request by wwwzzzcccc**
## Summary

Add document export functionality supporting both DOCX and PDF formats.

### DOCX Export (Pure Frontend)
- Built with `docx` (docx-js) library
- Supports: tables, math formulas (MathML→OMML), images, task lists, emoji, code blocks
- Comprehensive test coverage for all modules

### PDF Export (Backend Rendering)
- Uses Puppeteer server-side rendering
- Pairs with backend PR: Mininglamp-OSS/octo-docs-backend#16
- Supports: KaTeX math, CJK fonts (NotoSansSC), multi-page code blocks

### UI Changes
- New `ExportMenu` dropdown component replaces single export button
- Clean separation: DOCX/PDF/Print as separate menu items

### Print Fallback
- Browser print stylesheet for quick local printing without server dependency

## Related
- Backend PR: https://github.com/Mininglamp-OSS/octo-docs-backend/pull/16

### CODE REVIEW

**Review by OctoBoooot — CHANGES_REQUESTED** [review]
## Review: feat(docs): add DOCX and PDF export (#538)

**Verdict:** Request changes
This branch is **56 commits behind main and diverged** (`ahead 18 / behind 56`), which makes the diff unmergeable and unreviewable as-is: the `main...head` comparison shows **all 17 `.github/workflows/*` files being deleted** and core files like `EditorShell.tsx` shown as "added" when they already exist on main. These are artifacts of the stale merge base, not intentional changes — but merging as-is would revert 56 commits of infra/CI and other work. Please rebase on main and re-push before review can proceed. Risk tier: infra (the diff touches every workflow). `needs-human-review` applied (57 files / 7489 lines).

### Blocker
- **Rebase required — the diff would delete the entire CI/CD pipeline.** Against the current base, this PR removes all 17 workflows (`ci.yml`, `codeql.yml`, `dependency-review.yml`, `secret-scan.yml`, `docker-publish.yml`, `osv-scanner.yml`, `release-publish.yml`, …). Verified: `.github/workflows` has 18 files on `main` but only 4 on this head, and `compare/main...HEAD` reports `behind_by: 56, status: diverged`. This is a stale-branch artifact (the workflows landed in the 56 commits this branch is missing), so it's mechanical to fix — but until rebased, (a) the diff is not safe to merge (it reverts infra), and (b) CI signal is meaningless here (the branch's own workflow set is stale, which is why Build/osv-scan don't even appear in the checks). Rebase on `main`, resolve, re-push.

### Why I'm not reviewing the export code in depth yet
With a 56-commit-behind base, the `main...head` diff is dominated by merge-base noise — files modified on main (e.g. `EditorShell.tsx`) show as "added", real deletions mix with drift artifacts, and I can't cleanly isolate this PR's actual contribution from what main already changed. Reviewing the DOCX/PDF logic against this diff would produce findings that are half about drift. The feature code is present (`packages/docs/src/export/docx` — 17 modules incl. tests like `math.test.ts`, `tables.ts`, `mathml-to-omml.ts`; `packages/docs/src/export/pdf` — 17 modules), and the structure looks reasonable at a glance, but a real review needs a clean diff.

### After the rebase, the things I'll focus on (flagging early so they're on your radar)
- **Size / split.** Even excluding the drift, this is a large feature (DOCX pure-frontend + PDF Puppeteer-backend + ExportMenu UI). Consider landing DOCX and PDF as separate PRs — each is independently reviewable and testable, and the PDF path depends on a backend PR (octo-docs-backend#16) that should land in lockstep.
- **CI must be green on the rebased branch** — in particular `i18n:check` (the last two docs PRs, #537, failed on hardcoded strings) and the `ExportMenu` user-facing strings routed through `t()`.
- **PDF backend coupling** — confirm the Puppeteer endpoint contract matches the backend PR, and that export fails safe (clear error, no hang) when the backend isn't deployed — the same "stuck on Loading" class the #536 docs-gate was built to avoid.

Net: I can't give the export feature a fair review against a 56-commit-stale, diverged base — the diff would delete the CI pipeline and misrepresents what actually changed. Rebase on main and re-push; then I'll review the DOCX/PDF code properly (and please consider splitting DOCX vs PDF). Request changes.

**Review by Jerry-Xin — CHANGES_REQUESTED** [review]
Summary: The docs export feature is relevant to this repository, but the PR has multiple merge-blocking integration issues.

🔴 Blocking

🔴 Critical — The PR deletes repository CI and security workflows unrelated to docs export.
`.github/workflows/ci.yml:1`, `.github/workflows/codeql.yml:1`, `.github/workflows/dependency-review.yml:1`, and `.github/workflows/secret-scan.yml:1` are deleted. This removes build, lint, i18n, dependency review, CodeQL, and secret scanning coverage from `main`. A feature PR must not disable project-wide release and security gates.

🔴 Critical — New runtime imports are not declared as package dependencies.
The new export modules import `docx`, `xml-js`, `mathjax-full`, `jspdf`, and `jspdf-autotable` at [packages/docs/src/export/docx/index.ts](/Users/mlamp/.openclaw/tmp/pr-review-c4cmu9v3/repo/packages/docs/src/export/docx/index.ts:11), [packages/docs/src/export/docx/math.ts](/Users/mlamp/.openclaw/tmp/pr-review-c4cmu9v3/repo/packages/docs/src/export/docx/math.ts:33), [packages/docs/src/export/pdf/index.ts](/Users/mlamp/.openclaw/tmp/pr-review-c4cmu9v3/repo/packages/docs/src/export/pdf/index.ts:11), and [packages/docs/src/export/pdf/tables.ts](/Users/mlamp/.openclaw/tmp/pr-review-c4cmu9v3/repo/packages/docs/src/export/pdf/tables.ts:6), but the PR does not update `packages/docs/package.json` or the lockfile. `@octo/docs` typecheck/build/test will fail to resolve these modules.

🔴 Critical — The wired PDF export calls a non-existent frontend API helper.
[EditorShell.tsx](/Users/mlamp/.openclaw/tmp/pr-review-c4cmu9v3/repo/packages/docs/src/editor/EditorShell.tsx:19) imports `exportDocPdf` from `../pages/docsApi.ts`, and [line 374](/Users/mlamp/.openclaw/tmp/pr-review-c4cmu9v3/repo/packages/docs/src/editor/EditorShell.tsx:374) calls it, but this PR does not add that export to `docsApi.ts`. The editor cannot compile as written. Add the API helper with an `arraybuffer`/blob-safe response path, or wire the existing frontend `exportDocToPdf` implementation intentionally.

🔴 Critical — New user-visible export labels are missing from locale resources.
[ExportMenu.tsx](/Users/mlamp/.openclaw/tmp/pr-review-c4cmu9v3/repo/packages/docs/src/editor/ExportMenu.tsx:50) uses `docs.toolbar.export`, and [lines 68 and 75](/Users/mlamp/.openclaw/tmp/pr-review-c4cmu9v3/repo/packages/docs/src/editor/ExportMenu.tsx:68) use `docs.toolbar.exportDocx` / `docs.toolbar.exportPdf`, but the PR does not update `packages/docs/src/i18n/en-US.json` or `zh-CN.json`. This violates the project i18n requirements and will show raw keys or fail i18n validation.

💬 Non-blocking

🟡 Warning — The print fallback is implemented but not exposed. `exportDocViaPrint` exists in [packages/docs/src/export/print/index.ts](/Users/mlamp/.openclaw/tmp/pr-review-c4cmu9v3/repo/packages/docs/src/export/print/index.ts:62), but `ExportMenu` only offers Markdown, DOCX, and PDF. If print fallback is part of the shipped feature, add a menu item and handler.

🟡 Warning — `octo-export-menu`, `octo-export-dropdown`, and `octo-export-item` have no matching CSS in the PR. The dropdown will render unpositioned/unstyled unless styles are added.

✅ Highlights

The DOCX export code has thoughtful coverage for math fallback, emoji font handling, task lists, numbering, and table layout. The export logic is also reasonably decomposed into focused modules.

**Review by yujiawei — CHANGES_REQUESTED** [review]
# Code Review — PR #538 (octo-web)

**Verdict: CHANGES_REQUESTED** · Head SHA `8c383947ba37534ec57b1c062803cee9fb927d1c` · base `main`

Reviewed against `main` (merge-base `a812a307`). The feature work (DOCX export especially) is substantial and generally well-structured with good test coverage. However there are blocking issues that must be resolved before merge: an out-of-scope mass deletion of CI/security workflows, an unresolved import that breaks the build, a large volume of unwired dead code, and several confirmed correctness bugs.

---

## 1. Scope / Spec compliance — ❌

### 1a. 🚨 BLOCKING — 17 CI & security workflows deleted (out of scope, security-critical)

This PR is titled *"add DOCX and PDF export"* but contains **17 separate `chore: remove workflow …` commits** deleting `.github/workflows/`. The removed files include security- and release-critical automation:

- `codeql.yml` (code scanning)
- `osv-scanner.yml` (dependency vuln scanning)
- `secret-scan.yml` (secret detection)
- `dependency-review.yml` (PR dependency review)
- `ci.yml` (build/test CI)
- plus `docker-publish.yml`, `docker-lint.yml`, `release-publish.yml`, `release-drafter.yml`, `pr-title-lint.yml`, `labeler.yml`, `stale.yml`, `history-check.yml`, `issue-welcome.yml`, `check-sprint.yml`, `auto-add-to-project.yml`, `workflow-sanity.yml`.

I verified that `codeql.yml`, `osv-scanner.yml`, `secret-scan.yml`, and `dependency-review.yml` are **unchanged on `main` since the merge-base**, so merging this PR **will delete them from `main`** — removing code-scanning, dependency/secret scanning, and CI enforcement for the whole repository. This is entirely unrelated to a docs-export feature and is a serious change to the repo's security posture.

**Required:** drop all 17 workflow-deletion commits from this PR. If some of these workflows genuinely need to be retired, that must be a separate, explicitly-reviewed PR — not bundled into a feature branch.

### 1b. 🚨 BLOCKING — unresolved import will break the build

`packages/docs/src/editor/EditorShell.tsx` (new file in this PR) imports:

```ts
import { exportDocPdf } from '../pages/docsApi.ts'   // line 19
import { getDoc, updateDocTitle } from '../pages/docsApi.ts'  // line 25
```

`getDoc`/`updateDocTitle` exist in `main`'s `docsApi.ts`, but **`exportDocPdf` does not exist anywhere** — not in this PR's diff, not on `main`. The wired handler calls it at `EditorShell.tsx:374` (`const bytes = await exportDocPdf(docId)`). After merging into `main` this is an unresolved import → type-check / build failure.

**Required:** either add the missing `exportDocPdf` (and the backend it depends on) or wire the PDF button to code that actually exists.

### 1c. Branch is severely diverged / CONFLICTING

GitHub reports `mergeable: CONFLICTING`. The merge-base predates the entire `packages/docs` package as it exists on `main` (the PR head tree only contains `docs/src/editor` + `docs/src/export`, whereas `main` has `attachments/`, `pages/`, `collab/`, an existing `EditorShell.tsx`, etc.). This PR needs a rebase onto current `main` before it can be meaningfully merged or its diff trusted. Please rebase and re-request review.

### 1d. PR description does not match the implementation

The description says *"PDF Export (Backend Rendering) — Uses Puppeteer server-side rendering."* The actual PDF code added here is a **client-side `jsPDF`** renderer (`export/pdf/`) plus a **`window.print()`** path (`export/print/`). No Puppeteer/backend code is in this PR. The wired button (1b) points at a non-existent backend function. Please reconcile the description with what is actually shipped.

---

## 2. Code Quality — Changes-Requested

Findings were produced by module-by-module review and then independently re-verified against the source. Severity uses P0 (correctness/security/data-loss/build-break), P1 (functional bug), P2 (nit/maintainability).

### P0

- **Build break** — see §1b (`exportDocPdf` unresolved import). Counted here as well because it breaks compilation, not just scope.

### Dead code (high-impact maintainability)

A large fraction of this PR is **never imported by any non-test file**:

- The entire client `export/pdf/` module (`index.ts` `exportDocToPdf` and its ~15 supporting files, ~2,500 LOC) — the live PDF button calls the (missing) backend `exportDocPdf` instead. Only the module's own tests import it.
- The entire `export/print/` module (`exportDocViaPrint`) — nothing imports it.
- A **2.5 MB** binary font `export/pdf/assets/NotoSansSC-Regular.ttf` is committed solely for the dead jsPDF path.

If the intended PDF strategy is backend Puppeteer, most of `export/pdf/` and all of `export/print/` should not be in the tree (or must be wired up). Shipping 2,500+ LOC and a 2.5 MB asset that nothing reaches is a significant maintenance liability. Please decide on one PDF strategy and remove the unused one.

### P1 (confirmed functional bugs — in the DOCX path, which IS live)

- **`export/docx/mathml-to-omml.ts:198-219` — n-ary operand over-absorption.** In `convertSequence`, an n-ary operator (∑/∫/∏) greedily pulls *all* trailing siblings into its `<m:e>` body up to the next relation operator. For `∑ x + y = z`, the `+ y` after the summand is incorrectly swept under the ∑ operand instead of staying at the top level. Produces mathematically wrong OMML for common expressions.

- **`export/pdf/math.ts:76-79` — stateful `/g` regex in loop guard.** `const fracRe = /…frac…/g` is used as `for (…; fracRe.test(s); …)`. Because `.test()` on a global regex advances `lastIndex`, the guard reads a stale offset against the rewritten string, so the multi-pass nesting the comment promises never actually runs — nested `\frac{\frac{a}{b}}{c}` is only partially converted and leaks a literal `frac`. (In the dead jsPDF path, but a clear bug; also flagged independently as the same root cause via `images-print`.) Fix: reset `lastIndex`/use a non-global test or loop on `s.includes('frac')`.

- **`export/pdf/images.ts:182-196` — image height never capped.** `getImageDimensions` clamps width to content width but never bounds height. A tall/portrait image (e.g. 400×4000) passes the width check unchanged and is drawn far taller than the page content height; jsPDF clips at the page edge, silently losing the bottom of the image. Fix: clamp height to content height, preserving aspect ratio. (Also in the dead jsPDF path.)

> Note: the two `math.ts`/`images.ts` P1s live in the currently-unwired jsPDF module. They are real bugs, but if that module is removed per the dead-code point above, they become moot. The **mathml-to-omml P1 is in the live DOCX path** and should be fixed regardless.

### P2 (selected — full list available; these are the notable ones)

DOCX (live path):
- `docx/marks.ts:108-112` — `highlight` mark is hardcoded to `'yellow'`, silently discarding the actual highlight color.
- `docx/marks.ts:118-122` — `fontSize` parsed with `parseFloat` and treated as pt ambiguously; only accepts `string`, ignores px vs pt.
- `docx/marks.ts:141-146` / `nodes.ts:415,395` — link/bookmark/attachment hrefs go into `ExternalHyperlink` with **no scheme allow-list**; `javascript:`/`file:`/UNC hrefs from pasted content pass through. Recommend an http/https/mailto allow-list (security-sensitive PR — worth a human check).
- `docx/nodes.ts:194-197` — a 2nd+ paragraph inside a list item loses list indentation (renders flush-left). Cosmetic.
- `docx/tables.ts:114-151` — column widths derived only from row 0; genuinely ragged tables would zero-out overflow columns (rectangular ProseMirror/GFM tables are unaffected).
- `docx/tables.ts:185-191` — `convertCellContent` drops block types with no inline content (nested table / image / code block inside a cell) → silent content loss in table cells. Worth confirming.
- `docx/mathml-to-omml.ts:261-263` — unsupported MathML (matrices, `\binom`/fenced, multiscripts) falls back to raw LaTeX text with only a `console.warn` — silent fidelity loss.

Image fetching (both DOCX + PDF paths):
- `docx/images.ts:86-97`, `pdf/images.ts:122-138` — direct image `src` from user content is fetched with no scheme/host allow-list. Client-side (not server SSRF) but a forced-GET / internal-endpoint-probe surface for a doc author; restrict to `https:`/`data:` before fetching non-resolved `src`.
- `docx/images.ts:104-117`, `pdf/images.ts:60-70,141-144` — no response-size cap before buffering/base64-encoding; large or hostile images inflate memory (~4× transient for the base64 path). Add a Content-Length / max-bytes guard.
- `pdf/images.ts:75-83` — MIME guessed by substring match on the URL; the actual response `Content-Type` is available but unused.

PDF/print (dead path — low priority unless kept):
- `pdf/tables.ts:41,56-60` — header detection uses only the last cell of row 0.
- `pdf/marks.ts:212-216` — color parsing assumes 6-digit hex; 3-digit/named/`rgb()` → NaN channels.
- `pdf/marks.ts:48-53` — subscript/superscript marks parsed but never rendered.
- `pdf/nodes.ts:286-297` — blockquote left bar skips intermediate pages for 3+ page children.
- `print/index.ts:41-47,105-112` — the injected `@media print` stylesheet is never removed; after one export, a normal browser Ctrl+P hides `#root` and prints a blank page (session-scoped, self-heals on reload).
- `print/index.ts:67,105-112` — concurrent `exportDocViaPrint` calls corrupt each other's shared-id print root and restore the wrong `document.title`.
- `pdf/math.ts:76` — `\dfrac`/`\tfrac` not handled; the `\\d?frac` pattern matches nonexistent `\0frac…\9frac` rather than `d`/`t` prefixes.
- `pdf/fonts.ts:139-142` — single Regular TTF aliased to bold/italic/bolditalic; emphasized CJK loses weight/slant (documented trade-off).

### Positive notes

- DOCX math XML is properly escaped (`escXml`/`escAttr` in `mathml-to-omml.ts`), no XML injection there.
- No `innerHTML`/`dangerouslySetInnerHTML`/`eval` in the new code; KaTeX rendered with `throwOnError:false`.
- Image fetches use `AbortController` timeouts and bounded concurrency.
- DOCX export has thorough unit tests (tables, math fallback, numbering, task lists, emoji).

---

## 3. Blind spots / coverage

- Could not run a build/type-check or the test suite in this environment (the PR head tree lacks the `docs` `package.json`/tsconfig present on `main` due to the stale base) — the build-break in §1b is inferred from static import analysis against `main`'s `docsApi.ts`; please confirm with a real CI build after rebase.
- The paired backend PR (octo-docs-backend#16) was not reviewed here; the PDF feature's real behavior depends on it and on the missing `exportDocPdf` client binding.
- Runtime/i18n keys (`docs.toolbar.exportPdf`, `exportError`) were not verified as defined.
- Because the branch is CONFLICTING against a stale base, the effective post-merge diff may differ from what was reviewed; a rebase + re-review is required.

---

## Summary

Blocking before merge: **(1)** remove the 17 out-of-scope CI/security workflow deletions, **(2)** fix the unresolved `exportDocPdf` import (build break), **(3)** rebase onto current `main` and resolve conflicts, **(4)** decide on a single PDF strategy and remove the unwired dead code + 2.5 MB font, **(5)** fix the live DOCX mathml-to-omml n-ary bug. The remaining P2s (esp. DOCX highlight color, link scheme allow-list, table-cell content drop) should be addressed or explicitly deferred.
